"""DSH Bridge — practical compatibility with DSH / Cordis plugin bundles.

Honest scope. DSH plugins are Cordis/TypeScript/Node bundles; Tacit is Python.
Rather than pretend to reimplement that runtime, this bridge does three things:

1. **MCP first.** Anything that exposes MCP just works — register it and go.
2. **Detect and import.** Given an npm package or command, decide whether it can
   run as an MCP server and, if so, add it to the MCP config.
3. **Scaffold the rest.** If it cannot be imported, generate a starter adapter
   under ``~/.tacit/adapters/<id>/`` that a human (or a coding agent) can finish.

The optional Node helper (``bridges/dsh-host.mjs``) is only offered when Node is
actually installed. Nothing here runs a package or installs anything.
"""

from __future__ import annotations

import json
import re
import shutil

from .. import config, mcp_registry

PLUGIN = {
    "id": "dsh_bridge",
    "name": "DSH Bridge",
    "description": "Import DSH/Cordis tooling via MCP, or scaffold an adapter when it cannot "
                   "be imported directly. Never installs or runs anything on its own.",
    "version": "0.1",
    "permissions": ["filesystem", "subprocess"],
    "token_budget": 0,
    "settings": [
        {"key": "mcp_hint", "label": "Default MCP command template",
         "type": "string", "default": "npx -y {package}"},
        {"key": "allow_scaffold", "label": "Allow generating adapter scaffolds",
         "type": "bool", "default": True},
    ],
}

_S = {"type": "string"}
_B = {"type": "boolean"}

# Command shapes that are very likely to be MCP servers already.
_MCP_HINTS = ("mcp", "modelcontextprotocol")

_SERVER_STUB = '''"""MCP server stub for {pid}.

Generated by the Tacit DSH Bridge. It speaks newline-delimited JSON-RPC over
stdio, which is all Tacit's MCP client needs.

Replace `TOOLS` with the tools this DSH plugin should expose, and implement
`_handle` so each tool name maps to real work.
"""

import json
import sys

TOOLS = [
    {{
        "name": "example_tool",
        "description": "Replace me: describe what this tool does.",
        "inputSchema": {{"type": "object", "properties": {{}}, "required": []}},
    }},
]

PROTOCOL_VERSION = "2024-11-05"


def _send(payload):
    sys.stdout.write(json.dumps(payload) + "\\n")
    sys.stdout.flush()


def _handle(name, arguments):
    # TODO: map the DSH plugin's behaviour here.
    return f"{{name}} is not implemented yet (arguments: {{arguments!r}})"


def main():
    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue
        try:
            msg = json.loads(line)
        except json.JSONDecodeError:
            continue
        method = msg.get("method")
        rid = msg.get("id")
        if method == "initialize":
            if rid is not None:
                _send({{"jsonrpc": "2.0", "id": rid, "result": {{
                    "protocolVersion": PROTOCOL_VERSION,
                    "capabilities": {{"tools": {{}}}},
                    "serverInfo": {{"name": "{pid}", "version": "0.0"}},
                }}}})
        elif method == "notifications/initialized":
            continue
        elif method == "tools/list":
            if rid is not None:
                _send({{"jsonrpc": "2.0", "id": rid, "result": {{"tools": TOOLS}}}})
        elif method == "tools/call":
            params = msg.get("params") or {{}}
            try:
                text = _handle(params.get("name"), params.get("arguments") or {{}})
                result = {{"content": [{{"type": "text", "text": str(text)}}]}}
            except Exception as exc:
                result = {{"content": [{{"type": "text", "text": f"error: {{exc}}"}}],
                          "isError": True}}
            if rid is not None:
                _send({{"jsonrpc": "2.0", "id": rid, "result": result}})
        elif rid is not None:
            _send({{"jsonrpc": "2.0", "id": rid,
                    "error": {{"code": -32601, "message": f"method not found: {{method}}"}}}})


if __name__ == "__main__":
    main()
'''

_README = """# Adapter for `{pid}`

Tacit's DSH Bridge could not load `{source}` automatically, so it generated this
scaffold instead. **Nothing here runs by itself.**

## What is missing

{missing}

## How to finish it

1. Implement `_handle` in `server.py` so each entry in `TOOLS` does real work.
2. Test it on its own:

       python {server}

3. Register it with Tacit:

       Settings -> MCP -> Add server
         command : {python}
         args    : {server_abs}

4. Once it answers `tools/list`, tick **enabled** and re-scan.

## Notes

* Transport is newline-delimited JSON-RPC over stdio; Tacit sends `initialize`,
  `notifications/initialized`, `tools/list` and `tools/call`.
* Keep tool descriptions short — every discovered schema is measured, and
  schemas only enter the prompt when the agent activates or the user pins them.
"""


def _setting(key: str, default):
    try:
        from .. import plugin_manager

        values = (plugin_manager.settings_of("dsh_bridge") or {}).get("values") or {}
        return values.get(key, default)
    except Exception:  # noqa: BLE001
        return default


def _load_state() -> dict:
    data = config.read_json(config.HOME / "dsh.json", {})
    if not isinstance(data, dict):
        data = {}
    data.setdefault("plugins", [])
    return data


def _save_state(data: dict) -> None:
    config.write_json(config.HOME / "dsh.json", data)


def _looks_like_mcp(name: str, command: str) -> bool:
    hay = f"{name} {command}".lower()
    return any(hint in hay for hint in _MCP_HINTS)


def _classify(entry: dict) -> dict:
    """working_native | working_bridge | partial | unsupported"""
    source = entry.get("source") or entry.get("package") or entry.get("name") or ""
    server_id = entry.get("server_id") or ""
    if server_id and any(s["id"] == server_id for s in mcp_registry.list_servers()):
        spec = next((s for s in mcp_registry.list_servers() if s["id"] == server_id), None)
        if spec and spec.get("state") == "running" and spec.get("tool_count"):
            return {"status": "working_native",
                    "detail": f"{spec['tool_count']} tool(s) via MCP",
                    "server_id": server_id}
        return {"status": "partial", "detail": "registered but not answering yet",
                "server_id": server_id}
    if _looks_like_mcp(entry.get("name", ""), entry.get("command", "")) and entry.get("command"):
        return {"status": "working_bridge", "detail": "looks like an MCP command",
                "server_id": ""}
    if shutil.which("node") and entry.get("package"):
        return {"status": "partial",
                "detail": "Node is available — an adapter scaffold can be generated"}
    return {"status": "unsupported",
            "detail": "no MCP surface detected; needs a hand-written adapter"}


def tools() -> list[dict]:
    return [
        {"type": "function", "function": {
            "name": "dsh_status",
            "description": "Show which DSH plugins are usable here and how (native MCP, "
                           "bridge, partial, or unsupported).",
            "parameters": {"type": "object", "properties": {}, "required": []}}},
        {"type": "function", "function": {
            "name": "dsh_import",
            "description": "Register a DSH plugin/package as an MCP server. Does not install "
                           "or run anything — the user still has to enable it.",
            "parameters": {"type": "object",
                           "properties": {"package": _S, "command": _S, "name": _S},
                           "required": ["package"]}}},
        {"type": "function", "function": {
            "name": "dsh_scaffold",
            "description": "Generate a starter MCP adapter for a plugin that cannot be "
                           "imported directly.",
            "parameters": {"type": "object", "properties": {"plugin_id": _S},
                           "required": ["plugin_id"]}}},
    ]


def call(name: str, args: dict, ctx: dict):
    args = args or {}
    if name == "dsh_status":
        state = _load_state()
        if not state["plugins"]:
            return ("No DSH plugins registered yet. Use dsh_import with an npm package or "
                    "command, or add an MCP server directly in Settings → MCP.")
        lines = []
        for entry in state["plugins"]:
            verdict = _classify(entry)
            lines.append(f"- {entry.get('name') or entry.get('package')}: "
                         f"{verdict['status']} — {verdict['detail']}")
        lines.append("\nPolicy: use MCP directly where possible; bridge the rest.")
        return "\n".join(lines)
    if name == "dsh_import":
        package = str(args.get("package") or "").strip()
        if not package:
            return "ERROR: package is required"
        command = str(args.get("command") or "").strip()
        if not command:
            template = str(_setting("mcp_hint", "npx -y {package}"))
            command = template.replace("{package}", package)
        parts = command.split()
        server_id = args.get("name") or re.sub(r"[^A-Za-z0-9_.-]+", "-", package).strip("-")
        res = mcp_registry.add_server({
            "id": server_id,
            "name": args.get("name") or package,
            "command": parts[0],
            "args": parts[1:],
            "enabled": False,           # never auto-enabled
            "plugin": "dsh_bridge",
        })
        if not res.get("ok"):
            return f"ERROR: {res.get('error')}"
        state = _load_state()
        state["plugins"].append({"name": args.get("name") or package, "package": package,
                                 "command": command, "server_id": server_id})
        _save_state(state)
        verdict = _classify({"name": package, "command": command, "server_id": server_id})
        return (f"registered '{server_id}' as an MCP server ({verdict['status']}). "
                f"Nothing was installed or launched — enable it in Settings → MCP and hit "
                f"Re-scan to discover its tools.")
    if name == "dsh_scaffold":
        if not _setting("allow_scaffold", True):
            return "ERROR: adapter scaffolding is turned off in DSH Bridge settings"
        pid = re.sub(r"[^A-Za-z0-9_.-]+", "-", str(args.get("plugin_id") or "").strip()).strip("-")
        if not pid:
            return "ERROR: plugin_id is required"
        target = config.ADAPTERS_DIR / pid
        target.mkdir(parents=True, exist_ok=True)
        server = target / "server.py"
        server.write_text(_SERVER_STUB.format(pid=pid), encoding="utf-8")
        import sys as _sys

        (target / "manifest.json").write_text(json.dumps({
            "id": pid, "name": args.get("plugin_id"), "description": "Tacit MCP adapter scaffold",
            "version": "0.0", "permissions": ["subprocess"], "token_budget": 0,
            "generated_by": "dsh_bridge", "todo": ["implement _handle", "define TOOLS"],
        }, indent=2), encoding="utf-8")
        (target / "README.md").write_text(_README.format(
            pid=pid, source=args.get("plugin_id"), server="server.py",
            server_abs=server, python=_sys.executable,
            missing="- the plugin's real behaviour is not implemented yet"),
            encoding="utf-8")
        return (f"scaffolded {target}\n"
                f"  README.md, manifest.json, server.py\n"
                f"Nothing was run. Register it in Settings → MCP when it answers tools/list.")
    return None
